- do config syntax checking before doing reload
Changed files:
    apache.init -> 1.36

diff --git a/apache.init b/apache.init
--- a/apache.init
+++ b/apache.init
@@ -82,7 +82,13 @@ case "$1" in
   reload|force-reload|graceful)
 	if [ -f /var/lock/subsys/httpd ]; then
 		msg_reloading httpd.${HTTPD_MPM}
-		daemon httpd.${HTTPD_MPM} $CFG -k graceful
+		httpd.${HTTPD_MPM} $CFG -t > /dev/null 2>&1
+		if [ $? -eq 0 ]; then
+    		    daemon httpd.${HTTPD_MPM} $CFG -k graceful
+		else
+		    fail
+		    echo "Configuration file syntax test failed."
+		fi
 		RETVAL=$?
 	else
 		msg_not_running httpd.${HTTPD_MPM} >&2
